on:
  workflow_call:
    inputs:
      go-version-file:
        default: go.mod
        description: |
          Path to the file that declares the Go version
        required: false
        type: string

      golangci-lint-version:
        default: "v1.55.2"
        description: |
          Set the version for golangci-lint
        required: false
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: ci/setup
        uses: mattermost/actions/plugin-ci/setup@c7a06bc642f72fc227deb2cae3af03cff72c0f0d
        with:
          go-version-file: ${{ inputs.go-version-file }}
          golangci-lint-version: ${{ inputs.golangci-lint-version }}

      - name: ci/lint
        uses: mattermost/actions/plugin-ci/lint@c7a06bc642f72fc227deb2cae3af03cff72c0f0d

  test:
    runs-on: ubuntu-latest
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: ci/setup
        uses: mattermost/actions/plugin-ci/setup@c7a06bc642f72fc227deb2cae3af03cff72c0f0d
        with:
          go-version-file: ${{ inputs.go-version-file }}
          golangci-lint-version: ${{ inputs.golangci-lint-version }}

      - name: ci/test
        uses: mattermost/actions/plugin-ci/test@c7a06bc642f72fc227deb2cae3af03cff72c0f0d

  build:
    runs-on: ubuntu-latest
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: ci/setup
        uses: mattermost/actions/plugin-ci/setup@c7a06bc642f72fc227deb2cae3af03cff72c0f0d
        with:
          go-version-file: ${{ inputs.go-version-file }}
          golangci-lint-version: ${{ inputs.golangci-lint-version }}

      - name: ci/build
        uses: mattermost/actions/plugin-ci/build@c7a06bc642f72fc227deb2cae3af03cff72c0f0d
